// AUTO-GENERATED by typescript-type-def

export type Params=((unknown)[]|Record<string,unknown>);
export type U32=number;
export type Request={"jsonrpc":"2.0";"method":string;"params"?:Params;"id"?:U32;};
export type I32=number;
export type Error={"code":I32;"message":string;"data"?:unknown;};
export type Response={"jsonrpc":"2.0";"id":(U32|null);"result"?:unknown;"error"?:Error;};
export type Message=(Request|Response);
